<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rpslMetaModel"
    nsURI="http://www.robotics.h-brs.de/rpsl" nsPrefix="RpslMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component_property_prototype"
        upperBound="-1" eType="#//Prototype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QoS" upperBound="-1" eType="#//Prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_type" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_prototype" upperBound="-1"
        eType="#//Prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorComponent" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" eType="#//Algorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingComponent" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" lowerBound="1"
        eType="#//Algorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="PerceptionGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        upperBound="-1" eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="1"
        upperBound="-1" eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sink" lowerBound="1" eType="#//InputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//OutputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complexity" eType="#//COMPLEXITY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmImplementation" eSuperTypes="#//Algorithm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm_property_prototype"
        upperBound="-1" eType="#//Prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="COMPLEXITY">
    <eLiterals name="CONSTANT"/>
    <eLiterals name="DOUBLE_LOG" value="1"/>
    <eLiterals name="LINEAR" value="2"/>
    <eLiterals name="EXPONENTIAL" value="3"/>
    <eLiterals name="ANYTIME" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCategory" upperBound="-1"
        eType="#//Category" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subConcept" upperBound="-1"
        eType="#//Concept" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        upperBound="-1" eType="#//Domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInstance" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//Concept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//AbstractInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prototype" lowerBound="1"
        upperBound="-1" eType="#//Prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prototype" eSuperTypes="#//AbstractInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prototype_element" lowerBound="1"
        upperBound="-1" eType="#//PrototypeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        upperBound="-1" eType="#//DomainDimension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalDimension" eSuperTypes="#//DomainDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interval" lowerBound="1"
        eType="#//Interval"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrdinalDimension" eSuperTypes="#//DomainDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ordinal" lowerBound="1"
        upperBound="-1" eType="#//Ordinal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NominalDimension" eSuperTypes="#//DomainDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="RatioDimension" eSuperTypes="#//DomainDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrototypeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prototype_dimension" lowerBound="1"
        eType="#//DomainDimension"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_circular" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower_bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper_bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive_type" lowerBound="1"
        eType="#//RPSL_PRIMITIVE_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SIMILARITY_METRIC">
    <eLiterals name="EUCLIDIAN_DISTANCE"/>
    <eLiterals name="JACCARD_DISTANCE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="REQUEST_SAMPLE_SPEC">
    <eLiterals name="LIST_OF_SAMPLE"/>
    <eLiterals name="SAMPLE_OF" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="request_sample_spec" lowerBound="1"
        eType="#//REQUEST_SAMPLE_SPEC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrototypeRequest" eSuperTypes="#//Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="request_similarity" lowerBound="1"
        eType="#//RequestSimilarity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request_prototype" lowerBound="1"
        eType="#//Prototype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintRequest" eSuperTypes="#//Request"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequestSimilarity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarity_metric" lowerBound="1"
        eType="#//SIMILARITY_METRIC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance_type" eType="#//RPSL_PRIMITIVE_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="has_distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RPSL_PRIMITIVE_TYPE">
    <eLiterals name="RPSL_BOOLEAN"/>
    <eLiterals name="RPSL_INT8" value="1"/>
    <eLiterals name="RPSL_INT16" value="2"/>
    <eLiterals name="RPSL_INT32" value="3"/>
    <eLiterals name="RPSL_UINT32" value="4"/>
    <eLiterals name="RPSL_INT64" value="5"/>
    <eLiterals name="RPSL_UINT64" value="6"/>
    <eLiterals name="RPSL_FLOAT32" value="7"/>
    <eLiterals name="RPSL_FLOAT64" value="8"/>
    <eLiterals name="RPSL_STRING" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ordinal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="has_rank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive_type" eType="#//RPSL_PRIMITIVE_TYPE"/>
  </eClassifiers>
</ecore:EPackage>
